### ISSUE TITLE
How can I train my own data

### ISSUE THREAD

**Issue by eclipse0922** [qq456cvb/CPPF2#5]
First of all, thank you for sharing your awsome work!

Synthetic data based training looks very useful.

How can I prepare my own data for training?
I checked your previouse work CPPF as README.md mentioned.

But It seems littlbe bit different from the previous one's config file.

Could you please add some information about this? 
From looking at the code, it seems like it just needs to be formatted in Real275. Is my assumption correct?

I appreciate you in advance.

**Comment by qq456cvb** [comment]
Hi thanks for your interest,

To train with your own data, you need to first preprocess and export DINO and SHOT features into `pkl` (pickle) files for later training (this is to speed up the training process as computing these features are sometimes slow). 

To do so, you need to modify the data path and model names to yours on L192 and L212 of class `ShapeNetDirectDataset` in `dataset.py`, and then use `dump_data` function to dump the data. The parameter `full_rot` indicates whether to train with full SO(3) random rotation sampling as in DiversePose 300 or just a subset of rotations (very small in-plane rotation, positive elevations) as in NOCS REAL275.

Since our method uses an ensemble from both DINO and SHOT features, after exporting the training data, you will need to run both `train_dino.py` and `train_shot.py` to train two separate models, one for visual clues and the other for geometric clues. Again, make sure the path in class `ShapeNetExportDataset` is consistent, and you may want to delete the lines of `blacklists`.

To evaluate your trained model, we provide a sample `demo.py` file to process a video stream of RGB-D frames. We also updated the README to reflect this. Let me know if you have any questions.

**Comment by eclipse0922** [comment]
@qq456cvb 
Great!!
Thank you for the detailed explanation. 
How aobut the items in `config.yaml`

This part seems to be related to the coordinate system based on ShapeNet data.
 If I use the same coordinate system, I don't need to modify it, right?
```
up: [0, 1, 0]
right: [1, 0, 0]
front: [0, 0, 1]
up_sym: False
```

Related Code
```
 generate_target_pairs(pred_pairs_scaled.cpu().numpy(),  np.array(cfg.up),   np.array(cfg.front),  np.array(cfg.right))                              

```

**Comment by qq456cvb** [comment]
Oh yes! these up, right and front definitions now have **no effect on the training stage** for CPPF++. It will affect the voting at inference stage though (https://github.com/qq456cvb/CPPF2/blob/main/demo.py#L245). During inference, we first vote the up axis and then the right axis, but the definition of up and right depends on the actual category that you are predicting. You can change up and right definition if you observe better results. Here, I am just providing a default one.

**Comment by eclipse0922** [comment]
I see. The rest of the configuration in the config.yaml file appears to be explained in the updated README.md. I appreciate your help

**Comment by qq456cvb** [comment]
Hi, we've also made a tutorial for custom object category training, you can check out `train_custom.ipynb` for more details.
